#!/usr/bin/env bash
# Display To infintiy and beyond in a loop and "I am invincible!!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' 15
while true; do
	echo "To infinity and beyond"
	sleep 2
done 
