#!/usr/bin/env bash
# Display numbers 1 - 100 but replaces multiples of 3 and 5 with fizz and buzz
for (( i=0; i < 100; i++ ))
do
    if [ $((i%15)) = 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i%3)) = 0 ]
    then
	
	 echo "Fizz"
    elif [ $((i%5)) = 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi    
done
