#!/usr/bin/env bash
# Display the time by hour and minutes until 12 hours 59 minutes
m=1
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    while [ $m -lt 60 ]
    do
	echo $m
	m=$(( $m + 1))
    done
    h=$(( $h + 1 ))
    m=1
done
